// frontend/src/components/AppHeader.tsx
import { useAppStore } from '../store/appStore'
import styles from './AppHeader.module.css'

export function AppHeader() {
  const status = useAppStore((s) => s.status)
  const statusError = useAppStore((s) => s.statusError)

  const recording = status?.is_recording
  const analyzing = status?.is_analyzing
  const cams = status?.cameras_available

  return (
    <header className={styles.header}>
      <div>
        <p className={styles.brand}>SwingLab</p>
        <h1>Camera Setup &amp; Recording</h1>
      </div>
      <div className={styles.badges}>
        <span className={`${styles.badge} ${cams ? styles.ok : styles.warn}`}>
          {cams ? 'Cameras ready' : 'Cameras offline'}
        </span>
        {recording && <span className={`${styles.badge} ${styles.rec}`}>Recording</span>}
        {analyzing && <span className={`${styles.badge} ${styles.info}`}>Analyzing</span>}
        {status?.fps != null && (
          <span className={styles.badge}>Target {status.fps} fps</span>
        )}
      </div>
      {(status?.status_message || statusError) && (
        <div className={styles.message} role="status">
          {statusError || status?.status_message}
        </div>
      )}
    </header>
  )
}

// frontend/src/components/AppHeader.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useAppStore } from '../store/appStore'
import styles from './AppHeader.module.css'

const appStore = useAppStore()

const recording = computed(() => appStore.status?.is_recording)
const analyzing = computed(() => appStore.status?.is_analyzing)
const cams = computed(() => appStore.status?.cameras_available)
const message = computed(() => appStore.statusError || appStore.status?.status_message)
</script>

<template>
  <header :class="styles.header">
    <div>
      <p :class="styles.brand">SwingLab</p>
      <h1>Camera Setup &amp; Recording</h1>
    </div>
    <div :class="styles.badges">
      <span :class="[styles.badge, cams ? styles.ok : styles.warn]">
        {{ cams ? 'Cameras ready' : 'Cameras offline' }}
      </span>
      <span v-if="recording" :class="[styles.badge, styles.rec]">Recording</span>
      <span v-if="analyzing" :class="[styles.badge, styles.info]">Analyzing</span>
      <span v-if="appStore.status?.fps != null" :class="styles.badge">
        Target {{ appStore.status.fps }} fps
      </span>
    </div>
    <div v-if="message" :class="styles.message" role="status">
      {{ message }}
    </div>
  </header>
</template>
