// frontend/src/components/PropertySliders.vue
<script setup lang="ts">
import { computed, onUnmounted, ref, watch } from 'vue'
import { api, formatPropValue } from '../api/client'
import type { CameraProperties } from '../api/types'
import { PROP_ORDER } from '../api/types'
import styles from './PropertySliders.module.css'

interface Props {
  cameraNum: 1 | 2
  active: boolean
}

const props = defineProps<Props>()

const cameraProps = ref<CameraProperties | null>(null)
const error = ref<string | null>(null)
const local = ref<Record<string, number>>({})
const debounce: Record<string, ReturnType<typeof setTimeout>> = {}
let intervalId: ReturnType<typeof setInterval> | undefined

async function refresh() {
  try {
    const data = await api.cameraProperties(props.cameraNum)
    if (data.error) {
      error.value = data.error
      cameraProps.value = null
      return
    }

    error.value = null
    cameraProps.value = data
    const next: Record<string, number> = {}
    for (const name of PROP_ORDER) {
      const item = data[name]
      if (item) next[name] = item.value
    }
    local.value = next
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Failed to load properties'
  }
}

const info = computed(() => cameraProps.value?._info)

const rows = computed(() => {
  const data = cameraProps.value
  if (!data) return []
  return PROP_ORDER.filter((name) => data[name]).map((name) => ({
    name,
    ...data[name],
    value: local.value[name] ?? data[name].value,
  }))
})

function onChange(name: string, value: number) {
  local.value = { ...local.value, [name]: value }
  clearTimeout(debounce[name])
  debounce[name] = setTimeout(() => {
    void api.setCameraProperty(props.cameraNum, name, value).catch(() => {})
  }, 50)
}

watch(
  () => [props.active, props.cameraNum] as const,
  () => {
    if (intervalId) clearInterval(intervalId)
    intervalId = undefined
    if (!props.active) return
    void refresh()
    intervalId = setInterval(() => void refresh(), 2000)
  },
  { immediate: true },
)

onUnmounted(() => {
  if (intervalId) clearInterval(intervalId)
  for (const id of Object.values(debounce)) clearTimeout(id)
})
</script>

<template>
  <div v-if="error" :class="styles.error">{{ error }}</div>
  <div v-else-if="!cameraProps" :class="styles.loading">Loading properties...</div>
  <div v-else :class="styles.wrap">
    <p v-if="info" :class="styles.info">
      {{ info.width }}x{{ info.height }} @ {{ Number(info.fps || 0).toFixed(1) }} fps
    </p>
    <div :class="styles.list">
      <label v-for="row in rows" :key="row.name" :class="styles.row">
        <span :class="styles.label">{{ row.name.replace('_', ' ') }}</span>
        <input
          type="range"
          :min="row.min"
          :max="row.max"
          :step="row.step"
          :value="row.value"
          @input="onChange(row.name, Number(($event.target as HTMLInputElement).value))"
        />
        <span :class="styles.value">{{ formatPropValue(row.name, row.value) }}</span>
      </label>
    </div>
  </div>
</template>

// frontend/src/components/PropertySliders.tsx
import { useEffect, useMemo, useRef, useState } from 'react'
import { api, formatPropValue } from '../api/client'
import type { CameraProperties } from '../api/types'
import { PROP_ORDER } from '../api/types'
import styles from './PropertySliders.module.css'

interface Props {
  cameraNum: 1 | 2
  active: boolean
}

export function PropertySliders({ cameraNum, active }: Props) {
  const [props, setProps] = useState<CameraProperties | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [local, setLocal] = useState<Record<string, number>>({})
  const debounce = useRef<Record<string, ReturnType<typeof setTimeout>>>({})

  const refresh = async () => {
    try {
      const data = await api.cameraProperties(cameraNum)
      if (data.error) {
        setError(data.error)
        setProps(null)
        return
      }
      setError(null)
      setProps(data)
      const next: Record<string, number> = {}
      for (const name of PROP_ORDER) {
        const p = data[name]
        if (p) next[name] = p.value
      }
      setLocal(next)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load properties')
    }
  }

  useEffect(() => {
    if (!active) return
    void refresh()
    const id = setInterval(() => void refresh(), 2000)
    return () => clearInterval(id)
  }, [active, cameraNum])

  const info = props?._info

  const rows = useMemo(() => {
    if (!props) return []
    return PROP_ORDER.filter((name) => props[name]).map((name) => ({
      name,
      ...props[name],
      value: local[name] ?? props[name].value,
    }))
  }, [props, local])

  const onChange = (name: string, value: number) => {
    setLocal((prev) => ({ ...prev, [name]: value }))
    clearTimeout(debounce.current[name])
    debounce.current[name] = setTimeout(() => {
      void api.setCameraProperty(cameraNum, name, value).catch(() => {})
    }, 50)
  }

  if (error) {
    return <div className={styles.error}>{error}</div>
  }

  if (!props) {
    return <div className={styles.loading}>Loading properties…</div>
  }

  return (
    <div className={styles.wrap}>
      {info && (
        <p className={styles.info}>
          {info.width}×{info.height} @ {Number(info.fps || 0).toFixed(1)} fps
        </p>
      )}
      <div className={styles.list}>
        {rows.map((row) => (
          <label key={row.name} className={styles.row}>
            <span className={styles.label}>{row.name.replace('_', ' ')}</span>
            <input
              type="range"
              min={row.min}
              max={row.max}
              step={row.step}
              value={row.value}
              onChange={(e) => onChange(row.name, Number(e.target.value))}
            />
            <span className={styles.value}>{formatPropValue(row.name, row.value)}</span>
          </label>
        ))}
      </div>
    </div>
  )
}
