// frontend/src/components/TabBar.vue
<script setup lang="ts">
import { TABS, useAppStore } from '../store/appStore'
import styles from './TabBar.module.css'

const appStore = useAppStore()
</script>

<template>
  <nav :class="styles.bar" role="tablist" aria-label="Main">
    <button
      v-for="tab in TABS"
      :key="tab.id"
      type="button"
      role="tab"
      :aria-label="`${tab.shortcut} ${tab.label}`"
      :aria-selected="appStore.tab === tab.id"
      :class="appStore.tab === tab.id ? styles.active : undefined"
      @click="appStore.setTab(tab.id)"
    >
      <span :class="styles.key">{{ tab.shortcut }}</span>
      {{ tab.label }}
    </button>
  </nav>
</template>

// frontend/src/components/TabBar.tsx
import { TABS, useAppStore } from '../store/appStore'
import styles from './TabBar.module.css'

export function TabBar() {
  const tab = useAppStore((s) => s.tab)
  const setTab = useAppStore((s) => s.setTab)

  return (
    <nav className={styles.bar} role="tablist" aria-label="Main">
      {TABS.map((t) => (
        <button
          key={t.id}
          type="button"
          role="tab"
          aria-selected={tab === t.id}
          className={tab === t.id ? styles.active : undefined}
          onClick={() => setTab(t.id)}
        >
          <span className={styles.key}>{t.shortcut}</span>
          {t.label}
        </button>
      ))}
    </nav>
  )
}
