// frontend/src/App.tsx
import { useEffect } from 'react'
import { api } from './api/client'
import { AppHeader } from './components/AppHeader'
import { TabBar } from './components/TabBar'
import { AnalysisPage } from './features/analysis/AnalysisPage'
import { ComparePage } from './features/compare/ComparePage'
import { ProgressPage } from './features/progress/ProgressPage'
import { RecordingPage } from './features/recording/RecordingPage'
import { RecordingsPage } from './features/recordings/RecordingsPage'
import { CameraSetupPage } from './features/setup/CameraSetupPage'
import { SettingsPage } from './features/settings/SettingsPage'
import { useStatusPoll } from './hooks/useStatusPoll'
import { TABS, useAppStore } from './store/appStore'
import styles from './App.module.css'

export default function App() {
  useStatusPoll()
  const tab = useAppStore((s) => s.tab)
  const setTab = useAppStore((s) => s.setTab)
  const status = useAppStore((s) => s.status)

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      const tag = (e.target as HTMLElement)?.tagName
      if (tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT') return

      if (e.code === 'Space') {
        e.preventDefault()
        if (tab !== 'recording') setTab('recording')
        if (status?.auto_detect_enabled) return
        const recording = Boolean(status?.is_recording)
        void (async () => {
          try {
            if (recording) await api.stopRecording()
            else await api.startRecording()
          } catch {
            /* status poll will surface messages */
          }
        })()
        return
      }

      const match = TABS.find((t) => t.shortcut === e.key)
      if (match) setTab(match.id)
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [setTab, tab, status?.auto_detect_enabled, status?.is_recording])

  return (
    <div className={styles.app}>
      <AppHeader />
      <TabBar />
      <main className={styles.main} role="tabpanel">
        {tab === 'camera1' && <CameraSetupPage cameraNum={1} />}
        {tab === 'camera2' && <CameraSetupPage cameraNum={2} />}
        {tab === 'recording' && <RecordingPage />}
        {tab === 'recordings' && <RecordingsPage />}
        {tab === 'analysis' && <AnalysisPage />}
        {tab === 'compare' && <ComparePage />}
        {tab === 'progress' && <ProgressPage />}
        {tab === 'settings' && <SettingsPage />}
      </main>
    </div>
  )
}

// frontend/src/App.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'
import { api } from './api/client'
import AppHeader from './components/AppHeader.vue'
import TabBar from './components/TabBar.vue'
import { useStatusPoll } from './composables/useStatusPoll'
import AnalysisPage from './features/analysis/AnalysisPage.vue'
import ComparePage from './features/compare/ComparePage.vue'
import ProgressPage from './features/progress/ProgressPage.vue'
import RecordingPage from './features/recording/RecordingPage.vue'
import RecordingsPage from './features/recordings/RecordingsPage.vue'
import CameraSetupPage from './features/setup/CameraSetupPage.vue'
import SettingsPage from './features/settings/SettingsPage.vue'
import { TABS, useAppStore } from './store/appStore'
import styles from './App.module.css'

useStatusPoll()

const appStore = useAppStore()

function isFormField(target: EventTarget | null) {
  const tag = (target as HTMLElement | null)?.tagName
  return tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT'
}

function onKey(event: KeyboardEvent) {
  if (isFormField(event.target)) return

  if (event.code === 'Space') {
    event.preventDefault()
    if (appStore.tab !== 'recording') appStore.setTab('recording')
    if (appStore.status?.auto_detect_enabled) return
    const recording = Boolean(appStore.status?.is_recording)
    void (async () => {
      try {
        if (recording) await api.stopRecording()
        else await api.startRecording()
      } catch {
        /* status poll will surface messages */
      }
    })()
    return
  }

  const match = TABS.find((tab) => tab.shortcut === event.key)
  if (match) appStore.setTab(match.id)
}

onMounted(() => {
  window.addEventListener('keydown', onKey)
})

onUnmounted(() => {
  window.removeEventListener('keydown', onKey)
})
</script>

<template>
  <div :class="styles.app">
    <AppHeader />
    <TabBar />
    <main :class="styles.main" role="tabpanel">
      <CameraSetupPage v-if="appStore.tab === 'camera1'" :camera-num="1" />
      <CameraSetupPage v-else-if="appStore.tab === 'camera2'" :camera-num="2" />
      <RecordingPage v-else-if="appStore.tab === 'recording'" />
      <RecordingsPage v-else-if="appStore.tab === 'recordings'" />
      <AnalysisPage v-else-if="appStore.tab === 'analysis'" />
      <ComparePage v-else-if="appStore.tab === 'compare'" />
      <ProgressPage v-else-if="appStore.tab === 'progress'" />
      <SettingsPage v-else-if="appStore.tab === 'settings'" />
    </main>
  </div>
</template>
