// frontend/src/features/analysis/AnalysisPlayback.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { analysisFrameUrl, api } from '../../api/client'
import { PlaybackSequencer, playIntervalMs } from './playbackSequencer'
import styles from './AnalysisPlayback.module.css'

const SPEEDS = [0.25, 0.5, 1, 2, 4]

interface Props {
  maxFrames: number
  initialIndex?: number
}

const props = withDefaults(defineProps<Props>(), {
  initialIndex: 0,
})

const emit = defineEmits<{
  results: [data: unknown]
}>()

const index = ref(props.initialIndex)
const playing = ref(false)
const speedIdx = ref(2)
const bust = ref(0)
let sequencer: PlaybackSequencer | null = null
let timer: ReturnType<typeof setTimeout> | undefined

const speed = computed(() => SPEEDS[speedIdx.value])
const urls = computed(() => ({
  cam1: analysisFrameUrl(1, index.value, bust.value),
  cam2: analysisFrameUrl(2, index.value, bust.value),
}))

function clearPlaybackTimer() {
  if (timer) clearTimeout(timer)
  timer = undefined
}

function scheduleTick() {
  clearPlaybackTimer()
  if (!playing.value || props.maxFrames <= 1) return

  const tick = () => {
    const next = index.value + 1
    if (next >= props.maxFrames) {
      playing.value = false
      return
    }
    sequencer?.request(next)
    timer = setTimeout(tick, playIntervalMs(speed.value))
  }

  timer = setTimeout(tick, playIntervalMs(speed.value))
}

function togglePlaying() {
  playing.value = !playing.value
}

function cycleSpeed() {
  speedIdx.value = (speedIdx.value + 1) % SPEEDS.length
}

function onSeek(event: Event) {
  playing.value = false
  sequencer?.request(Number((event.target as HTMLInputElement).value))
}

onMounted(() => {
  sequencer = new PlaybackSequencer(
    async (frameIndex) => {
      const data = await api.setAnalysisFrame(frameIndex)
      emit('results', data)
      bust.value += 1
    },
    (frameIndex) => {
      index.value = frameIndex
    },
  )
})

watch([playing, speed, () => props.maxFrames], scheduleTick)

onUnmounted(() => {
  clearPlaybackTimer()
  sequencer?.dispose()
})
</script>

<template>
  <div v-if="maxFrames <= 0" :class="styles.empty">
    No annotated frames yet - record and analyze a swing.
  </div>
  <div v-else :class="styles.wrap">
    <div :class="styles.dual">
      <img :src="urls.cam1" alt="Camera 1 analysis" />
      <img :src="urls.cam2" alt="Camera 2 analysis" />
    </div>
    <div :class="styles.controls">
      <button type="button" @click="togglePlaying">{{ playing ? 'Pause' : 'Play' }}</button>
      <button type="button" @click="cycleSpeed">{{ speed }}x</button>
      <input
        type="range"
        min="0"
        :max="Math.max(0, maxFrames - 1)"
        :value="index"
        @input="onSeek"
      />
      <span :class="styles.meta">{{ index + 1 }} / {{ maxFrames }}</span>
    </div>
  </div>
</template>

// frontend/src/features/analysis/AnalysisPlayback.tsx
import { useEffect, useMemo, useRef, useState } from 'react'
import { analysisFrameUrl, api } from '../../api/client'
import { PlaybackSequencer, playIntervalMs } from './playbackSequencer'
import styles from './AnalysisPlayback.module.css'

const SPEEDS = [0.25, 0.5, 1, 2, 4]

interface Props {
  maxFrames: number
  initialIndex?: number
  onResults?: (data: unknown) => void
}

export function AnalysisPlayback({ maxFrames, initialIndex = 0, onResults }: Props) {
  const [index, setIndex] = useState(initialIndex)
  const [playing, setPlaying] = useState(false)
  const [speedIdx, setSpeedIdx] = useState(2)
  const [bust, setBust] = useState(0)
  const seqRef = useRef<PlaybackSequencer | null>(null)

  const speed = SPEEDS[speedIdx]

  useEffect(() => {
    const seq = new PlaybackSequencer(async (i) => {
      const data = await api.setAnalysisFrame(i)
      onResults?.(data)
      setBust((b) => b + 1)
    }, setIndex)
    seqRef.current = seq
    return () => seq.dispose()
  }, [onResults])

  useEffect(() => {
    if (!playing || maxFrames <= 1) return
    let cancelled = false
    let timer: ReturnType<typeof setTimeout> | undefined

    const tick = () => {
      if (cancelled) return
      const next = index + 1
      if (next >= maxFrames) {
        setPlaying(false)
        return
      }
      seqRef.current?.request(next)
      timer = setTimeout(tick, playIntervalMs(speed))
    }

    timer = setTimeout(tick, playIntervalMs(speed))
    return () => {
      cancelled = true
      if (timer) clearTimeout(timer)
    }
  }, [playing, speed, maxFrames, index])

  const urls = useMemo(
    () => ({
      cam1: analysisFrameUrl(1, index, bust),
      cam2: analysisFrameUrl(2, index, bust),
    }),
    [index, bust],
  )

  if (maxFrames <= 0) {
    return <div className={styles.empty}>No annotated frames yet — record and analyze a swing.</div>
  }

  return (
    <div className={styles.wrap}>
      <div className={styles.dual}>
        <img src={urls.cam1} alt="Camera 1 analysis" />
        <img src={urls.cam2} alt="Camera 2 analysis" />
      </div>
      <div className={styles.controls}>
        <button type="button" onClick={() => setPlaying((p) => !p)}>
          {playing ? 'Pause' : 'Play'}
        </button>
        <button
          type="button"
          onClick={() => setSpeedIdx((i) => (i + 1) % SPEEDS.length)}
        >
          {speed}x
        </button>
        <input
          type="range"
          min={0}
          max={Math.max(0, maxFrames - 1)}
          value={index}
          onChange={(e) => {
            setPlaying(false)
            seqRef.current?.request(Number(e.target.value))
          }}
        />
        <span className={styles.meta}>
          {index + 1} / {maxFrames}
        </span>
      </div>
    </div>
  )
}
