// frontend/src/features/progress/ProgressPage.tsx
import { useEffect, useMemo, useState } from 'react'
import { api } from '../../api/client'
import type { ProgressResponse } from '../../api/types'
import { LineChart } from '../../components/LineChart'
import styles from './ProgressPage.module.css'

const COLORS = ['#58a6ff', '#3fb950', '#f0883e', '#d2a8ff', '#79c0ff', '#f85149', '#d29922']

export function ProgressPage() {
  const [data, setData] = useState<ProgressResponse | null>(null)
  const [enabled, setEnabled] = useState<Record<string, boolean>>({ score: true })
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    void api
      .progress()
      .then((res) => {
        setData(res)
        const next: Record<string, boolean> = {}
        for (const m of res.metrics || []) {
          next[m.key] = m.key === 'score'
        }
        setEnabled(next)
      })
      .catch((err) => setError(err instanceof Error ? err.message : 'Failed to load progress'))
  }, [])

  const series = useMemo(() => {
    if (!data) return []
    return (data.metrics || [])
      .filter((m) => enabled[m.key])
      .map((m, i) => ({
        label: m.label,
        color: COLORS[i % COLORS.length],
        values: data.series[m.key] || [],
      }))
  }, [data, enabled])

  const labels = useMemo(
    () => (data?.points || []).map((p) => p.date || p.timestamp || ''),
    [data],
  )

  return (
    <section className={styles.page}>
      <header className={styles.header}>
        <div>
          <h2>Progress</h2>
          <p>Trends across saved analyses (oldest → newest).</p>
        </div>
        {data && (
          <div className={styles.summary}>
            <span>
              Swings: <strong>{data.count}</strong>
            </span>
            <span>
              Latest:{' '}
              <strong>
                {data.latest_grade || '—'}{' '}
                {data.latest_score != null ? Math.round(data.latest_score) : ''}
              </strong>
            </span>
            <span>
              Δ score:{' '}
              <strong
                className={
                  data.score_delta == null
                    ? undefined
                    : data.score_delta >= 0
                      ? styles.up
                      : styles.down
                }
              >
                {data.score_delta == null
                  ? '—'
                  : `${data.score_delta > 0 ? '+' : ''}${data.score_delta}`}
              </strong>
            </span>
          </div>
        )}
      </header>

      {error && <p className={styles.error}>{error}</p>}

      {data && (
        <>
          <div className={styles.toggles}>
            {(data.metrics || []).map((m, i) => (
              <label key={m.key}>
                <input
                  type="checkbox"
                  checked={Boolean(enabled[m.key])}
                  onChange={(e) =>
                    setEnabled((prev) => ({ ...prev, [m.key]: e.target.checked }))
                  }
                />
                <i style={{ background: COLORS[i % COLORS.length] }} />
                {m.label}
              </label>
            ))}
          </div>
          <LineChart series={series} labels={labels} height={300} />
          {!data.count && (
            <p className={styles.empty}>No analyzed swings yet — progress appears after analysis JSON is saved.</p>
          )}
        </>
      )}
    </section>
  )
}

// frontend/src/features/progress/ProgressPage.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { api } from '../../api/client'
import type { ProgressResponse } from '../../api/types'
import LineChart from '../../components/LineChart.vue'
import styles from './ProgressPage.module.css'

const COLORS = ['#58a6ff', '#3fb950', '#f0883e', '#d2a8ff', '#79c0ff', '#f85149', '#d29922']

const data = ref<ProgressResponse | null>(null)
const enabled = ref<Record<string, boolean>>({ score: true })
const error = ref<string | null>(null)

const series = computed(() => {
  if (!data.value) return []
  return (data.value.metrics || [])
    .filter((metric) => enabled.value[metric.key])
    .map((metric, index) => ({
      label: metric.label,
      color: COLORS[index % COLORS.length],
      values: data.value?.series[metric.key] || [],
    }))
})

const labels = computed(() => (data.value?.points || []).map((point) => point.date || point.timestamp || ''))

onMounted(() => {
  void api
    .progress()
    .then((res) => {
      data.value = res
      const next: Record<string, boolean> = {}
      for (const metric of res.metrics || []) {
        next[metric.key] = metric.key === 'score'
      }
      enabled.value = next
    })
    .catch((err) => {
      error.value = err instanceof Error ? err.message : 'Failed to load progress'
    })
})

function setMetricEnabled(key: string, event: Event) {
  enabled.value = {
    ...enabled.value,
    [key]: (event.target as HTMLInputElement).checked,
  }
}
</script>

<template>
  <section :class="styles.page">
    <header :class="styles.header">
      <div>
        <h2>Progress</h2>
        <p>Trends across saved analyses (oldest -&gt; newest).</p>
      </div>
      <div v-if="data" :class="styles.summary">
        <span>Swings: <strong>{{ data.count }}</strong></span>
        <span>
          Latest:
          <strong>
            {{ data.latest_grade || '-' }}
            {{ data.latest_score != null ? Math.round(data.latest_score) : '' }}
          </strong>
        </span>
        <span>
          &Delta; score:
          <strong
            :class="
              data.score_delta == null
                ? undefined
                : data.score_delta >= 0
                  ? styles.up
                  : styles.down
            "
          >
            {{
              data.score_delta == null
                ? '-'
                : `${data.score_delta > 0 ? '+' : ''}${data.score_delta}`
            }}
          </strong>
        </span>
      </div>
    </header>

    <p v-if="error" :class="styles.error">{{ error }}</p>

    <template v-if="data">
      <div :class="styles.toggles">
        <label v-for="(metric, index) in data.metrics || []" :key="metric.key">
          <input
            type="checkbox"
            :checked="Boolean(enabled[metric.key])"
            @change="setMetricEnabled(metric.key, $event)"
          />
          <i :style="{ background: COLORS[index % COLORS.length] }" />
          {{ metric.label }}
        </label>
      </div>
      <LineChart :series="series" :labels="labels" :height="300" />
      <p v-if="!data.count" :class="styles.empty">
        No analyzed swings yet - progress appears after analysis JSON is saved.
      </p>
    </template>
  </section>
</template>
