// frontend/src/features/recording/ChecklistPanel.vue
<script setup lang="ts">
import type { ChecklistResponse } from '../../api/types'
import styles from './ChecklistPanel.module.css'

interface Props {
  checklist: ChecklistResponse | null
}

defineProps<Props>()
</script>

<template>
  <div :class="styles.panel">
    <template v-if="!checklist">
      <h3>Pre-Record Checklist</h3>
      <p :class="styles.muted">Checking cameras...</p>
    </template>
    <template v-else>
      <div :class="styles.head">
        <h3>Pre-Record Checklist</h3>
        <span :class="checklist.ready ? styles.ready : styles.notReady">
          {{ checklist.ready ? 'Ready' : 'Not Ready' }}
        </span>
      </div>
      <ul :class="styles.list">
        <li
          v-for="item in checklist.items || []"
          :key="item.id"
          :class="item.ok ? styles.ok : item.required ? styles.bad : styles.warn"
        >
          <span :class="styles.mark">
            <template v-if="item.ok">&#10003;</template>
            <template v-else>&#10007;</template>
          </span>
          <span><strong>{{ item.label }}</strong> &mdash; {{ item.detail }}</span>
        </li>
      </ul>
      <p v-if="checklist.usb_warning" :class="styles.usb">{{ checklist.usb_warning }}</p>
    </template>
  </div>
</template>

// frontend/src/features/recording/ChecklistPanel.tsx
import type { ChecklistResponse } from '../../api/types'
import styles from './ChecklistPanel.module.css'

interface Props {
  checklist: ChecklistResponse | null
}

export function ChecklistPanel({ checklist }: Props) {
  if (!checklist) {
    return (
      <div className={styles.panel}>
        <h3>Pre-Record Checklist</h3>
        <p className={styles.muted}>Checking cameras…</p>
      </div>
    )
  }

  return (
    <div className={styles.panel}>
      <div className={styles.head}>
        <h3>Pre-Record Checklist</h3>
        <span className={checklist.ready ? styles.ready : styles.notReady}>
          {checklist.ready ? 'Ready' : 'Not Ready'}
        </span>
      </div>
      <ul className={styles.list}>
        {(checklist.items || []).map((item) => {
          const cls = item.ok ? styles.ok : item.required ? styles.bad : styles.warn
          return (
            <li key={item.id} className={cls}>
              <span className={styles.mark}>{item.ok ? '✓' : '✗'}</span>
              <span>
                <strong>{item.label}</strong> — {item.detail}
              </span>
            </li>
          )
        })}
      </ul>
      {checklist.usb_warning && (
        <p className={styles.usb}>{checklist.usb_warning}</p>
      )}
    </div>
  )
}
