// frontend/src/features/recording/RecordingPage.vue
<script setup lang="ts">
import { computed, onUnmounted, ref, watch } from 'vue'
import { api } from '../../api/client'
import type { ChecklistResponse } from '../../api/types'
import CameraPreview from '../../components/CameraPreview.vue'
import { useAppStore } from '../../store/appStore'
import AutoDetectPanel from './AutoDetectPanel.vue'
import ChecklistPanel from './ChecklistPanel.vue'
import PracticeTools from './PracticeTools.vue'
import styles from './RecordingPage.module.css'

const appStore = useAppStore()
const busy = ref(false)
const error = ref<string | null>(null)
const checklist = ref<ChecklistResponse | null>(null)
let checklistInterval: ReturnType<typeof setInterval> | undefined

const recording = computed(() => Boolean(appStore.status?.is_recording))
const autoOn = computed(() => Boolean(appStore.status?.auto_detect_enabled))
const label1 = computed(() => appStore.status?.camera_labels?.camera1 || 'Face-On')
const label2 = computed(() => appStore.status?.camera_labels?.camera2 || 'Down-the-Line')
const resolutionText = computed(
  () => `${appStore.status?.width || 1280}x${appStore.status?.height || 720} @ ${appStore.status?.fps || 120}fps`,
)

async function refreshChecklist() {
  try {
    checklist.value = await api.checklist()
  } catch {
    /* ignore */
  }
}

watch(
  () => [recording.value, appStore.status?.is_analyzing] as const,
  () => {
    if (checklistInterval) clearInterval(checklistInterval)
    checklistInterval = undefined
    void refreshChecklist()
    if (recording.value || appStore.status?.is_analyzing) return
    checklistInterval = setInterval(() => void refreshChecklist(), 2000)
  },
  { immediate: true },
)

watch(
  () => appStore.status?.is_analyzing,
  (isAnalyzing) => {
    if (isAnalyzing) appStore.setTab('analysis')
  },
)

onUnmounted(() => {
  if (checklistInterval) clearInterval(checklistInterval)
})

async function toggleRecord() {
  busy.value = true
  error.value = null
  try {
    const result = recording.value ? await api.stopRecording() : await api.startRecording()
    if (result.error) {
      error.value = result.error
      if ('checklist' in result && result.checklist) checklist.value = result.checklist
    } else if (!recording.value) {
      await refreshChecklist()
    }
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Recording failed'
  } finally {
    busy.value = false
  }
}

async function toggleAuto() {
  busy.value = true
  error.value = null
  try {
    const data = await api.toggleAutoDetect()
    if (data.error) {
      error.value = data.error
      if (data.checklist) checklist.value = data.checklist
    } else {
      await refreshChecklist()
    }
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Auto-detect failed'
  } finally {
    busy.value = false
  }
}
</script>

<template>
  <section :class="styles.page">
    <div :class="[styles.dual, autoOn ? styles.autoActive : '']">
      <CameraPreview
        :camera-num="1"
        active
        :session="appStore.streamSession"
        :recording="recording"
        :label="`Camera 1 (${label1})`"
      />
      <CameraPreview
        :camera-num="2"
        active
        :session="appStore.streamSession"
        :recording="recording"
        :label="`Camera 2 (${label2})`"
      />
    </div>

    <div :class="styles.controls">
      <div :class="styles.statusRow">
        <span :class="[styles.dot, recording ? styles.dotLive : '']" />
        <div>
          <div :class="styles.label">
            {{ autoOn ? 'Auto-detect armed' : recording ? 'Recording' : 'Ready to record' }}
          </div>
          <div :class="styles.detail">{{ resolutionText }} &middot; Space to start/stop</div>
        </div>
        <span
          v-if="recording && appStore.status?.recording_duration != null"
          :class="styles.duration"
        >
          {{ appStore.status.recording_duration.toFixed(1) }}s
        </span>
      </div>

      <div :class="styles.buttons">
        <button
          v-if="!autoOn"
          type="button"
          :class="recording ? styles.stop : styles.start"
          :disabled="busy"
          @click="toggleRecord"
        >
          {{ recording ? 'Stop recording' : 'Start recording' }}
        </button>
        <label :class="styles.toggle">
          <input
            type="checkbox"
            :checked="autoOn"
            :disabled="busy || recording"
            @change="toggleAuto"
          />
          Auto detect
        </label>
      </div>

      <AutoDetectPanel :enabled="autoOn" :status="appStore.status?.auto_detect_status" />
      <p v-if="error" :class="styles.error">{{ error }}</p>
    </div>

    <ChecklistPanel :checklist="checklist" />
    <PracticeTools />
  </section>
</template>

// frontend/src/features/recording/RecordingPage.tsx
import { useEffect, useState } from 'react'
import { api } from '../../api/client'
import type { ChecklistResponse } from '../../api/types'
import { CameraPreview } from '../../components/CameraPreview'
import { useAppStore } from '../../store/appStore'
import { AutoDetectPanel } from './AutoDetectPanel'
import { ChecklistPanel } from './ChecklistPanel'
import { PracticeTools } from './PracticeTools'
import styles from './RecordingPage.module.css'

export function RecordingPage() {
  const status = useAppStore((s) => s.status)
  const streamSession = useAppStore((s) => s.streamSession)
  const setTab = useAppStore((s) => s.setTab)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [checklist, setChecklist] = useState<ChecklistResponse | null>(null)

  const recording = Boolean(status?.is_recording)
  const autoOn = Boolean(status?.auto_detect_enabled)
  const label1 = status?.camera_labels?.camera1 || 'Face-On'
  const label2 = status?.camera_labels?.camera2 || 'Down-the-Line'

  const refreshChecklist = async () => {
    try {
      const data = await api.checklist()
      setChecklist(data)
    } catch {
      /* ignore */
    }
  }

  useEffect(() => {
    void refreshChecklist()
    if (recording || status?.is_analyzing) return
    const id = setInterval(() => void refreshChecklist(), 2000)
    return () => clearInterval(id)
  }, [recording, status?.is_analyzing])

  // After stop+analyze, jump to Analysis when results appear
  useEffect(() => {
    if (status?.is_analyzing) setTab('analysis')
  }, [status?.is_analyzing, setTab])

  const toggleRecord = async () => {
    setBusy(true)
    setError(null)
    try {
      const result = recording ? await api.stopRecording() : await api.startRecording()
      if (result.error) {
        setError(result.error)
        if ('checklist' in result && result.checklist) setChecklist(result.checklist)
      } else if (!recording) {
        await refreshChecklist()
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Recording failed')
    } finally {
      setBusy(false)
    }
  }

  const toggleAuto = async () => {
    setBusy(true)
    setError(null)
    try {
      const data = await api.toggleAutoDetect()
      if (data.error) {
        setError(data.error)
        if (data.checklist) setChecklist(data.checklist)
      } else {
        await refreshChecklist()
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Auto-detect failed')
    } finally {
      setBusy(false)
    }
  }

  return (
    <section className={styles.page}>
      <div className={`${styles.dual} ${autoOn ? styles.autoActive : ''}`}>
        <CameraPreview
          cameraNum={1}
          active
          session={streamSession}
          recording={recording}
          label={`Camera 1 (${label1})`}
        />
        <CameraPreview
          cameraNum={2}
          active
          session={streamSession}
          recording={recording}
          label={`Camera 2 (${label2})`}
        />
      </div>

      <div className={styles.controls}>
        <div className={styles.statusRow}>
          <span className={`${styles.dot} ${recording ? styles.dotLive : ''}`} />
          <div>
            <div className={styles.label}>
              {autoOn
                ? 'Auto-detect armed'
                : recording
                  ? 'Recording'
                  : 'Ready to record'}
            </div>
            <div className={styles.detail}>
              {status?.width || 1280}×{status?.height || 720} @ {status?.fps || 120}fps
              {' · '}
              Space to start/stop
            </div>
          </div>
          {recording && status?.recording_duration != null && (
            <span className={styles.duration}>
              {status.recording_duration.toFixed(1)}s
            </span>
          )}
        </div>

        <div className={styles.buttons}>
          {!autoOn && (
            <button
              type="button"
              className={recording ? styles.stop : styles.start}
              disabled={busy}
              onClick={() => void toggleRecord()}
            >
              {recording ? 'Stop recording' : 'Start recording'}
            </button>
          )}
          <label className={styles.toggle}>
            <input
              type="checkbox"
              checked={autoOn}
              disabled={busy || recording}
              onChange={() => void toggleAuto()}
            />
            Auto detect
          </label>
        </div>

        <AutoDetectPanel enabled={autoOn} status={status?.auto_detect_status} />
        {error && <p className={styles.error}>{error}</p>}
      </div>

      <ChecklistPanel checklist={checklist} />
      <PracticeTools />
    </section>
  )
}
